### ISSUE TITLE
Wrong package Github URL on hex.pm

### ISSUE THREAD

**Issue by 2kodes** [gutschilla/elixir-navigation-tree#1]
HI ,
just checked out your package on hex.pm. However on clicking on the Github link on this page, 
https://hex.pm/packages/navigation_tree, I was redirected to this page : https://github.com/gutschilla/plug-session-memcached. Should it not point to this page, https://github.com/gutschilla/elixir-navigation-tree rather?

**Comment by gutschilla** [comment]
Oops, thanks for this one. Going to fix this.
